import React from 'react';
import '../styles/mentorModal.css';
import mentorImage from '../img/cursedCat.png'; // Replace with the actual image path

export default function MentorModal({ name, img, description, isOpen, onClose, onConnect }) {
    if (!isOpen) {
        return null;
    }

    return (
        <div className="modal">
            <div className="modal-content">
                <h1>Mentor Name</h1>
                <img src={mentorImage} alt="Mentor" className="mentor-image" />
                <p>ASIDHAIUDHAIDSHIAUSDHIUASDH DESCRIPTION HERE ASJDGHAHJKDS GAKJHSDG KAHSJDGDHSDLAH SKAJSHHDKJHSD AKSH DKAS H KJDSHKJA HDKAJSH DKASH DKJAHS DKJAHSDKLJ HASDKA HSDKHASKHKS HKAH SKHDKALSH K HKS HKAH SKDAH SKDHKASHDKLASH DKLJSAH DKLJSAHDKLHAKS DKLSHDKASDKAHSDKLHSKDHAKSDH    KAS HDKHS DKH k KASBD JASBD HASB DJH JAHDA SDHAS DHAS DHAS DHAS DHGAS DHGAS DHGAS DHSA DHG ASDH ASHDG ASHG ADASJKDASKJHDASKJD ASD ASD A</p>
                <br></br>
                <p>ASIDHAIUDHAIDSHIAUSDHIUASDH DESCRIPTION HERE ASJDGHAHJKDS GAKJHSDG KAHSJDGDHSDLAH SKAJSHHDKJHSD AKSH DKAS H KJDSHKJA HDKAJSH DKASH DKJAHS DKJAHSDKLJ HASDKA HSDKHASKHKS HKAH SKHDKALSH K HKS HKAH SKDAH SKDHKASHDKLASH DKLJSAH DKLJSAHDKLHAKS DKLSHDKASDKAHSDKLHSKDHAKSDH    KAS HDKHS DKH k KASBD JASBD HASB DJH JAHDA SDHAS DHAS DHAS DHAS DHGAS DHGAS DHGAS DHSA DHG ASDH ASHDG ASHG ADASJKDASKJHDASKJD ASD ASD A</p>
                <br></br>
                <p>ASIDHAIUDHAIDSHIAUSDHIUASDH DESCRIPTION HERE ASJDGHAHJKDS GAKJHSDG KAHSJDGDHSDLAH SKAJSHHDKJHSD AKSH DKAS H KJDSHKJA HDKAJSH DKASH DKJAHS DKJAHSDKLJ HASDKA HSDKHASKHKS HKAH SKHDKALSH K HKS HKAH SKDAH SKDHKASHDKLASH DKLJSAH DKLJSAHDKLHAKS DKLSHDKASDKAHSDKLHSKDHAKSDH    KAS HDKHS DKH k KASBD JASBD HASB DJH JAHDA SDHAS DHAS DHAS DHAS DHGAS DHGAS DHGAS DHSA DHG ASDH ASHDG ASHG ADASJKDASKJHDASKJD ASD ASD A</p>
                <br></br>
                <p>ASIDHAIUDHAIDSHIAUSDHIUASDH DESCRIPTION HERE ASJDGHAHJKDS GAKJHSDG KAHSJDGDHSDLAH SKAJSHHDKJHSD AKSH DKAS H KJDSHKJA HDKAJSH DKASH DKJAHS DKJAHSDKLJ HASDKA HSDKHASKHKS HKAH SKHDKALSH K HKS HKAH SKDAH SKDHKASHDKLASH DKLJSAH DKLJSAHDKLHAKS DKLSHDKASDKAHSDKLHSKDHAKSDH    KAS HDKHS DKH k KASBD JASBD HASB DJH JAHDA SDHAS DHAS DHAS DHAS DHGAS DHGAS DHGAS DHSA DHG ASDH ASHDG ASHG ADASJKDASKJHDASKJD ASD ASD A</p>

                <button className="modal-connect" onClick={onConnect}>
                    Connect
                </button>
                <button className="modalClose" onClick={onClose}>
                    Close
                </button>
            </div>
        </div>
    );
}
